defaults: &defaults
  adapter: mysql2
  username: b5e65678394a46
  password: 8307469c

development:
  database: rails-db
  <<: *defaults

test:
  database: rails-db
  <<: *defaults

production:
  database: heroku_b3c9d8ef3d59b1e
  host: us-cdbr-iron-east-05.cleardb.net
  <<: *defaults