defaults: &defaults
  adapter: mysql2
  CLEARDB_DATABASE_URL: mysql2://b07eb759827a55:03e8ff0e@us-cdbr-iron-east-05.cleardb.net/heroku_8349d7c22f6b144?reconnect=true
  username: b07eb759827a55
  password: 03e8ff0e

development:
  database: rails-db
  <<: *defaults

test:
  database: rails-db
  <<: *defaults
  
production:
  adapter: mysql2
  encoding: utf8
  database: heroku_8349d7c22f6b144
  username: b07eb759827a55
  password: 03e8ff0e
  host: mysql2://b07eb759827a55:03e8ff0e@us-cdbr-iron-east-05.cleardb.net
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false