defaults: &defaults
  adapter: mysql2
  
  username: b07eb759827a55
  password: 03e8ff0e

development:
  database: rails-db
  <<: *defaults

test:
  database: rails-db
  <<: *defaults

production:
  database: heroku_8349d7c22f6b144
  host: '192.168.0.90'
  <<: *defaults