defaults: &defaults
  adapter: mysql2
  username: root
  password: 19950208

development:
  database: rails-db
  <<: *defaults

test:
  database: rails-db
  <<: *defaults

production:
  database: rails-db
  <<: *defaults