test:
  domain: yourmailgundomain.mailgun.org
  api_key: key-****-***************************

development:
  domain: yourmailgundomain.mailgun.org
  api_key: key-****-***************************

production:
  domain: yourmailgundomain.mailgun.org
  api_key: key-****-***************************
